{
	{'preheat': [], '#no-action#': []},
	{'beat': [['egg'], ['vanilla']], '#no-action#': [], 'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'add': [['flour']], '#no-action#': []},
	{'fold': [['chocolate', 'chips']], '#no-action#': []},
	{'drop': [], '#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'cream': [['butter'], ['sugar']]},
	{'mix': [], 'add': [['egg'], ['vanilla']], '#no-action#': []},
	{'#no-action#': [], 'combine': [['white', 'flour'], ['wheat', 'flour'], ['baking', 'soda'], ['salt'], ['butter'], ['egg']]},
	{'mix': [], '#no-action#': [], 'stir': [], 'pour': [['chocolate']]},
	{'press': [], '#no-action#': []},
	{'#no-action#': [], 'bake': [['brown']]},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [['chocolate']]},
	{'#no-action#': []},
	{'put': [], 'preheat': [], '#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'soda'], ['salt'], ['xanthan', 'gum']]},
	{'beat': [['shortening'], ['sugar']], '#no-action#': []},
	{'add': [['egg']], '#no-action#': []},
	{'beat': [['vanilla']], '#no-action#': []},
	{'stir': [['walnut'], ['chocolate', 'chips']], '#no-action#': [], 'reduce': [['flour']]},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': []},
	{'#no-action#': [], 'place': [], 'preheat': []},
	{'#no-action#': [], 'line':[]},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'powder'], ['salt'], ['baking', 'soda']]},
	{'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'beat': [['butter'], ['sugar'], ['brown', 'sugar']], '#no-action#': []},
	{'beat': [], 'add': [['egg']], '#no-action#': []},
	{'add': [], '#no-action#': [], 'reduce': []}, #DRY INGREDIENTS + WET INGREDIENTS??
	{'fold': [['chocolate']], '#no-action#': []},
	{'spoon': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'bake': [], 'cool': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': []},
	{'wrap': [], '#no-action#': [], 'freeze': []},
	{'#no-action#': []},
	{'#no-action#': [], 'store': [], 'freeze': []},
	{'#no-action#': []},
	{'position': [], '#no-action#': [], 'preheat': []},
	{'line':[]},
	{'#no-action#': [], 'sift': [['baking'], ['nonstick', 'baking']]},
	{'#no-action#': [], 'split': [['vanilla']], 'scrape': []},
	{'#no-action#': [], 'combine': [['vanilla'], ['dried', 'cherries']]},
};