import pickle

finalAssociations = [
	{'preheat': [], '#no-action#': []},
	{'beat': [['egg'], ['vanilla']], '#no-action#': [], 'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'add': [['flour']], '#no-action#': []},
	{'fold': [['chocolate', 'chips']], '#no-action#': []},
	{'drop': [], '#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'cream': [['butter'], ['sugar']]},
	{'mix': [], 'add': [['egg'], ['vanilla']], '#no-action#': []},
	{'#no-action#': [], 'combine': [['white', 'flour'], ['wheat', 'flour'], ['baking', 'soda'], ['salt'], ['butter'], ['egg']]},
	{'mix': [], '#no-action#': [], 'stir': [], 'pour': [['chocolate']]},
	{'press': [], '#no-action#': []},
	{'#no-action#': [], 'bake': [['brown']]},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [['chocolate']]},
	{'#no-action#': []},
	{'put': [], 'preheat': [], '#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'soda'], ['salt'], ['xanthan', 'gum']]},
	{'beat': [['shortening'], ['sugar']], '#no-action#': []},
	{'add': [['egg']], '#no-action#': []},
	{'beat': [['vanilla']], '#no-action#': []},
	{'stir': [['walnut'], ['chocolate', 'chips']], '#no-action#': [], 'reduce': [['flour']]},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': []},
	{'#no-action#': [], 'place': [], 'preheat': []},
	{'#no-action#': [], 'line':[]},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'powder'], ['salt'], ['baking', 'soda']]},
	{'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'beat': [['butter'], ['sugar'], ['brown', 'sugar']], '#no-action#': []},
	{'beat': [], 'add': [['egg']], '#no-action#': []},
	{'add': [], '#no-action#': [], 'reduce': []}, #DRY INGREDIENTS + WET INGREDIENTS??
	{'fold': [['chocolate']], '#no-action#': []},
	{'spoon': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'bake': [], 'cool': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': []},
	{'wrap': [], '#no-action#': [], 'freeze': []},
	{'#no-action#': []},
	{'#no-action#': [], 'store': [], 'freeze': []},
	{'#no-action#': []},
	{'position': [], '#no-action#': [], 'preheat': []},
	{'line':[]},
	{'#no-action#': [], 'sift': [['baking'], ['nonstick', 'baking']]},
	{'#no-action#': [], 'split': [['vanilla']], 'scrape': []},
	{'#no-action#': [], 'combine': [['vanilla'], ['cherry']]},
	{'#no-action#': [], 'drain': [['cherry'], ['vanilla', 'bean']]},
	{'beat': [], '#no-action#': [], 'combine': [['butter'], ['sugar'], ['brown', 'sugar']]},
	{'beat': [], 'add': [['egg'], ['vanilla', 'bean']], '#no-action#': []},
	{'add': [['flour']], '#no-action#': []},
	{'add': [['cherry'], ['white', 'chocolate'], ['semisweet', 'chocolate']], '#no-action#': [], 'stir': []},
	{'drop': [['baking', 'sheet']], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'#no-action#': [], 'continue':[]},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [], 'sift':[]},
	{'beat': [['butter'], ['hazelnut', 'butter'], ['sugar']], '#no-action#': []},
	{'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'beat': [['flour']], '#no-action#': []},
	{'#no-action#': [], 'stir': [['chocolate', 'chips']]},
	{'refrigerate': [], '#no-action#': [], 'cover': []},
	{'#no-action#': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': [], 'soften':[]},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [], 'roll': []},
	{'#no-action#': [], 'arrange': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': []},
	{'#no-action#': [], 'store': []},
	{'#no-action#': []},
	{'grease': [['butter']], '#no-action#': []},
	{'cut': [], '#no-action#': []},
	{'beat': [['butter'], ['egg'], ['vanilla'], ['sugar']], '#no-action#': []},
	{'#no-action#': [], 'stir': [['flour'], ['baking', 'soda'], ['salt']]},
	{'#no-action#': [], 'stir': [['butter']]},
	{'#no-action#': [], 'stir': [['walnut'], ['chocolate']]},
	{'spoon': [], '#no-action#': []},
	{'cook': [], '#no-action#': [], 'cover': []},
	{'#no-action#': [], 'set': []},
	{'turn': [], '#no-action#': [], 'remove': []},
	{'#no-action#': [], 'cool': []},
	{'#no-action#': [], 'invert':[]},
	{'cut': [], '#no-action#': []},
	{'#no-action#': [], 'serve': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'press': [], '#no-action#': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'mash': [['banana']]},
	{'#no-action#': []},
	{'#no-action#': [], 'place': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'serve': [], 'cool': []},
	{'make': [], '#no-action#': [], 'bake': [], 'cool': []},
	{'cut': [], '#no-action#': []},
	{'#no-action#': [], 'freeze': [], 'cool': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': [['banana']]},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'whip': [['water', 'flaxseed']]},
	{'#no-action#': [], 'set': []},
	{'mix': [['butter'], ['sugar']], '#no-action#': []},
	{'add': [['egg'], ['vanilla']], '#no-action#': []},
	{'#no-action#': [], 'blend': [['cocoa', 'powder'], ['baking', 'soda'], ['baking', 'powder'], ['salt'], ['flour']]},
	{'mix': [], 'add': [], '#no-action#': []},
	{'add': [['water']], '#no-action#': []},
	{'#no-action#': [], 'stir': ['chips']}, #could be chocolate?
	{'#no-action#': [], 'flatten': [], 'form': []},
	{'#no-action#': [], 'bake': []},
	{'scoop': [], '#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'line':[]},
	{'#no-action#': [], 'sift':[]},
	{'beat': [['butter']], '#no-action#': []},
	{'beat': [['egg'], ['sugar']], '#no-action#': []},
	{'beat': [['flour'], ['almond', 'extract'], ['vanilla','extract'] ], '#no-action#': []},
	{'fold': ['chocolate'], '#no-action#': []},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'flatten': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'reverse':[]},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'#no-action#': [], 'freeze': []},
	{'spoon': [], '#no-action#': []},
	{'top': [], '#no-action#': []},
	{'wrap': [], '#no-action#': [], 'freeze': []},
	{'#no-action#': [], 'repeat': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'line': [], '#no-action#': []},
	{'mix': [['oil'], ['salt'], ['vanilla'], ['juice'], ['applesauce']], '#no-action#': []},
	{'#no-action#': [], 'whisk': [['flour'], ['flax'], ['baking', 'soda'], ['xanthan', 'gum']]},
	{'add': [], '#no-action#': [], 'stir': []},
	{'fold': [['chocolate']], '#no-action#': []},
	{'scoop': [], '#no-action#': []},
	{'press': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'store': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'sift': [['flour'], ['baking', 'soda'], ['salt']], '#no-action#': []},
	{'beat': [['butter'], ['vegetable', 'shortening']], '#no-action#': []},
	{'beat': [], 'add': [['sugar'], ['brown', 'sugar'], ['sour', 'cream'], ['vanilla']], '#no-action#': []},
	{'beat': [['egg'], ['flour']], '#no-action#': []},
	{'#no-action#': [], 'stir': [['chocolate']]},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'flatten': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'repeat': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'soda'], ['baking', 'powder'], ['salt'], ['oat']]},
	{'#no-action#': [], 'cream': [['butter'], ['sugar']]},
	{'beat': [['vanilla'], ['egg']], '#no-action#': []}, #1091
	{'beat': [['flour']], '#no-action#': [], 'stir': [['chocolate']]},
	{'drop': [], '#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'whisk': [['flour'], ['baking', 'soda'], ['salt']]},
	{'#no-action#': [], 'cream': [['butter'], ['sugar']]},
	{'beat': [['flour'], ['egg']], '#no-action#': []},
	{'beat': [['vanilla']], '#no-action#': [], 'stir': [['coconut'], ['chocolate']]},
	{'drop': [], '#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'keep': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'butter':[]},
	{'beat': [['vegetable', 'shortening'], ['butter']], '#no-action#': []},
	{'beat': [], 'add': [['sugar']], '#no-action#': []},
	{'add': [['egg']], '#no-action#': []},
	{'add': [['vanilla', 'pudding'], ['vanilla', 'extract'], ['baking', 'soda'], ['water'], ['cinnamon'], ['nutmeg'], ['salt']], '#no-action#': []},
	{'mix': [['oat'], ['flour']], '#no-action#': []},
	{'#no-action#': [], 'stir': [['chocolate'], ['walnut']]},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'#no-action#': [], 'cool': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
	{'#no-action#': [], 'store': []},
	{'#no-action#': []},
	{'preheat': [], '#no-action#': []},
	{'#no-action#': [], 'grease': []},
	{'beat': [['margarine'], ['sugar']], '#no-action#': []},
	{'beat': [['egg'], ['vanilla']], '#no-action#': []},
	{'sift': [['flour'], ['baking', 'soda'], ['salt'], ['margarine']], '#no-action#': [], 'stir': []},
	{'mix': [['oat'], ['chocolate', 'chips'], ['pecan']], '#no-action#': []},
	{'drop': [], '#no-action#': []},
	{'#no-action#': [], 'bake': []},
	{'transfer': [], '#no-action#': [], 'cool': []},
];

pickle.dump(finalAssociations, open( "ground_truth_cookie.p", "wb" ) )